### ISSUE TITLE
Importing multiple versions

### ISSUE THREAD

**Issue by simoncolmer** [oriel-hub/OKHub-Content-WordPress#3]
Example:
- Import 10 documents with the Country "Peru" from the source Eldis
- Manual import
- Documents created as expected (tempate extracts "Hub metadata" - displays at bottom of each document)
- Amend import and add the source "ELLA" with the same Country "Peru" filter.
- Manual import
- Document that exists in both sources is imported "twice" e.g. http://wordpress.dev.ids.ac.uk/index.php/okhub_documents/land-grabbing-in-latin-america-opportunity-or-threat/ but the document version imported later, does not have any of the "Hub metadata" despite the metadata being recorded in the WordPress custom fields.

This is probably not ideal behaviour. 

Am not sure what plan we have for handling versions in WP, so may be easier to add a new "Preferred source" function/filter that imports by preferred source over other sources, where two versions exist.

**Comment by simoncolmer** [comment]
Much more expected behaviour now, although with small bug.
- Import 10 documents with the Country "Philippines" from the source SERP-P
- Manual import
- Documents created as expected (SERP-P description imported into WP description field)
- Amend import and add the source "Eldis" with the same Country "Philippines" filter.
- Manual import
- Document amended, leaving originally imported description in place, and metadata (from new source) populated.
  HOWEVER
  description metadata field populated with the original imported field content. 
  e.g. the eldis_description_en contains the same content as the serpp_description_en (rather than the eldis_description_en content).

**Comment by accuosto** [comment]
Thanks, Simon. It should be fixed now.
I updated the changed files in your dev server, tested it and it seems to be working ok.
Could you please confirm if we can close this issue?

**Comment by simoncolmer** [comment]
Brilliant. Thank you.
Fixed and closed.
