### ISSUE TITLE
JSON error when saving settings/manual import

### ISSUE THREAD

**Issue by simoncolmer** [oriel-hub/OKHub-Content-WordPress#4]
- Change import settings, click Save
- Settings saved 
- Click on Manual Import button

Get Request failed error
"Output {"readyState":0,"responseText":"","responseJSON":null,"status":0,"statusText":"error"}

**Comment by accuosto** [comment]
An ajax call was still running when the 'Manual import' button was clicked and it failed to return valid results. I had included the message for debugging purposes, but in general it doesn't imply an error, so I now disabled it.

**Comment by simoncolmer** [comment]
Thank you!
