### ISSUE TITLE
JQuery errors on category filters tab

### ISSUE THREAD

**Issue by simoncolmer** [oriel-hub/OKHub-Content-WordPress#5]
"Uncaught TypeError: Cannot read property 'length' of undefined"

Categories do not load to enable selection.

Think this appears to be a timing out issue. The issues with each taxonomy for each source are not generally repeatable, so could just be multiple jquery threads running at the same time.

From testing, there were issues with displaying pick lists for the following Source/Category:

Eldis / Themes
Open Docs / Themes
BRIDGE  / All categories
HEART / All categories
IGIDR / Doc types
Observ Action / Themes, Countries, Doc types
3ie, CCCCC, ELLA, SERPP, Soulbeat / Themes

**Comment by pmasonids** [comment]
This also seems to be a problem for another site, where there are no themes to select.
It's a very generic error message, so hard to diagnose. 
We can provide an example site if this would be useful.

**Comment by accuosto** [comment]
An example site would be useful. Thanks.

**Comment by pmasonids** [comment]
Fixed (I think). The code was requesting hub_theme_context, which wasn't a general field in the API. Now added, and the list of Eldis themes works. This would mean it was permissions-related (based on API key) which fits with only some people having the problem.

Simon, could you check for those other related issues you were having?

**Comment by simoncolmer** [comment]
Categories now loaded as expected. 
Thank you.
Closed.
